# Generated by Django 3.1.14 on 2023-10-16 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20231012_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=200, verbose_name='Название покемона на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=200, verbose_name='Название покемона на японском'),
            preserve_default=False,
        ),
    ]
