# Generated by Django 3.1.14 on 2023-10-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20231017_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='parent',
            new_name='previous_evolution',
        ),
    ]
